name: Create and publish a Docker image

on:
  push:
    branches: ['main', 'ci-test']

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Build And Push
        uses: whoan/docker-build-with-cache-action@v5
        with:
          username: ${{ github.actor }}
          password: "${{ secrets.GITHUB_TOKEN }}"
          image_tag: ${{ github.sha }},${{ github.ref_name }}
          registry: ghcr.io
          image_name: x11base
